# Generated by Django 5.1.7 on 2025-09-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("room_name", models.CharField(max_length=20)),
                ("max_rows", models.IntegerField()),
                ("max_columns", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "seat_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="room.room",
                    ),
                ),
            ],
        ),
    ]
