# Generated by Django 5.2.5 on 2025-08-14 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.faculty')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.year')),
            ],
            options={
                'unique_together': {('name', 'year', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.faculty')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.year')),
            ],
            options={
                'unique_together': {('name', 'class_name', 'year', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.year')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
            options={
                'unique_together': {('exam', 'room_number', 'seat_number')},
            },
        ),
    ]
